/**
 * Company
 * Company API provides functionality to create and update a company type resource
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rafael.guzman1609@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Notification } from './notification';

export class EmptyDataResponse {
    'data'?: string;
    'notification'?: Notification;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
      {
        name: 'data',
        baseName: 'data',
        type: 'string'
      },
      {
        name: 'notification',
        baseName: 'notification',
        type: 'Notification'
      }];

    static getAttributeTypeMap() {
      return EmptyDataResponse.attributeTypeMap;
    }
}
