/**
 * Company
 * Company API provides functionality to create and update a company type resource
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rafael.guzman1609@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Notification {
    /**
    * level:   * INFO - Informative notification.   * WARNING - Warning notification, something may have happened with the request.   * ERROR - Error notification, some error may have occurred with the request.
    */
    'level'?: Notification.LevelEnum;
    /**
    * Code to identify the notification and classify according to the first character (E) Error,(W) Warning,(I) Info.
    */
    'code'?: string;
    /**
    * Human-friendly error or notification message.
    */
    'message'?: string;
    /**
    * [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) Date and time when the notification happened.
    */
    'timestamp'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
      {
        name: 'level',
        baseName: 'level',
        type: 'Notification.LevelEnum'
      },
      {
        name: 'code',
        baseName: 'code',
        type: 'string'
      },
      {
        name: 'message',
        baseName: 'message',
        type: 'string'
      },
      {
        name: 'timestamp',
        baseName: 'timestamp',
        type: 'Date'
      }];

    static getAttributeTypeMap() {
      return Notification.attributeTypeMap;
    }
}

export namespace Notification {
    export enum LevelEnum {
        Info = <any> 'INFO',
        Warning = <any> 'WARNING',
        Error = <any> 'ERROR'
    }
}
